### PR TITLE
translated newest strings (root)

### PR DESCRIPTION
**Pull request by rbarat**
Please merge. Thanks

### CODE REVIEW

**Comment by xyyx** [comment]
Make for all your language in one commit, please

**Comment by rbarat** [comment]
Made changes for slovak and czech -> two pull requests.

2017-04-19 12:48 GMT+02:00 Max <notifications@github.com>:

**Comment by rbarat** [comment]
How in one commit? Made two pull request - for czech and slovak laguages.

**Comment by xyyx** [comment]
No. One pull with one commit for both files.

**Comment by rbarat** [comment]
Hi,

do not understand what do you want: "One pull with one commit for both files".
How can I make one pull request for two languages?

There are two modified files:
android_packages_apps_Settings/res/values-cs/nitrogen_strings.xml
android_packages_apps_Settings/res/values-sk/nitrogen_strings.xml

I do not know how to make it in one request.

Tell me please.

Robert

**Pull request closed without merging**
